version: '1'
services:
  base:
    image: "mysql"
    container_name: 'Base_Mysql'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - base_mysql:/var/lib/mysql      
    ports:
      - "3306:3306"

volumes:
  base_mysql: 