version: '3'
services:
  base:
    image: mysql
    container_name: 'Base_Mysql'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - base_mysql:/var/lib/mysql      
    ports:
      - "3306:3306"
  backend:
    image: luisamariao/backend:v1
    container_name: 'Backend_Node'
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST='base'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='secret'
      - MYSQL_DATABASE='proyecto1'
    restart: always
    #depends_on:
    #  - base

  frontend:
    image: luisamariao/frontend:v1
    container_name: 'Frontend-React'
    ports:
      - "3000:3000"
volumes:
  base_mysql: 