version: '3'
services:
  base:
    image: mysql
    container_name: 'Base_Mysql'
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - base_mysql:/var/lib/mysql      
    ports:
      - "3306:3306"
  backend:
    image: luisamariao/backend:v1
    container_name: 'Backend_Node'
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST='base'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='secret'
      - MYSQL_DATABASE='proyecto1'
    restart: always
    depends_on:
      - base

  frontend:
    image: luisamariao/frontend:v4
    container_name: 'Frontend-React'
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://34.105.25.226:8080
    restart: always
    depends_on:
      - backend
networks:
  mynetwork:
volumes:
  base_mysql: 