FROM golang:1.18

WORKDIR /app

COPY go.mod . 
COPY main.go .

RUN go build -o bin . 
EXPOSE 5000
ENTRYPOINT [ "/app/bin" ]
#sudo docker build . -t agente
#sudo docker run --privileged --pid=host -p 5000:5000 agente 